import pandas as pd


def flights_dataset():
    df = pd.read_csv('flights_data_002.csv')
    df = df.drop(['conversion'], axis=1)
    df['local_arrival'] = pd.to_datetime(df['local_arrival'])
    df['local_departure'] = pd.to_datetime(df['local_departure'])
    grouped_bag = df.groupby('distance')
    grouped_avl = df.groupby('distance')

    df['bags_price'] = grouped_bag['bags_price'].apply(lambda x: x.fillna(x.dropna().iloc[0]) if x.isnull().values.any() else x)
    df['availability'] = grouped_avl['availability'].apply(lambda x: x.fillna(x.dropna().iloc[0]) if x.isnull().values.any() else x)
    city_category_scores = {
    ('Málaga', 'Beach'): 8,
    ('Alicante', 'Beach'): 7,
    ('Almería', 'Beach'): 6,
    ('Asturias', 'Nature'): 9,
    ('Bilbao', 'Cultural'): 8,
    ('Barcelona', 'Cultural'): 9,
    ('Badajoz', 'Nature'): 7,
    ('Béziers', 'Adventurous'): 6,
    ('Brindisi', 'Adventurous'): 7,
    ('Donostia / San Sebastián', 'Nature'): 8,
    ('Fuerteventura', 'Beach'): 7,
    ('Girona', 'Cultural'): 8,
    ('Granada', 'Historical'): 9,
    ('Ibiza', 'Beach'): 7,
    ('Jerez de la Frontera', 'Cultural'): 7,
    ('A Coruña', 'Nature'): 8,
    ('Lanzarote', 'Beach'): 6,
    ('Madrid', 'Historical'): 9,
    ('Agadir', 'Beach'): 6,
    ('Menorca', 'Beach'): 7,
    ('Melilla', 'Historical'): 8,
    ('Palma, Majorca', 'Beach'): 8,
    ('Pamplona', 'Historical'): 7,
    ('Santander', 'Nature'): 8,
    ('Seville', 'Historical'): 9,
    ('Tenerife', 'Beach'): 7,
    ('Valencia', 'Cultural'): 8,
    ('Valladolid', 'Cultural'): 7,
    ('Vigo', 'Nature'): 7,
    ('Vitoria-Gasteiz', 'Nature'): 7,
    ('Valverde', 'Nature'): 6,
    ('Zaragoza', 'Cultural'): 8,
    ('Santiago de Compostela', 'Historical'): 8}
    cities = [key[0] for key in city_category_scores.keys()]
    categories = [key[1] for key in city_category_scores.keys()]
    scores = list(city_category_scores.values())

    df['category'] = df['cityTo'].apply(lambda x: categories[cities.index(x)] if x in cities else None)
    df['score'] = df['cityTo'].apply(lambda x: scores[cities.index(x)] if x in cities else None)
    df = df.drop(['fare', 'luggage_weight','availability','local_arrival','airlines','score','bags_price','countryTo'],axis=1)
    df['Description'] = df['cityTo'].map({
    "Málaga": "A coastal city on the southern coast of Spain known for its Mediterranean climate and stunning beaches, including La Malagueta and Playa del Palo. The historic center is home to charming streets, tapas bars, and landmarks like the Cathedral of Málaga and the Roman Theatre. Art enthusiasts can visit the Picasso Museum, which displays the works of the famous artist who was born in Málaga. Visitors can also explore the nearby Costa del Sol, which offers picturesque towns and beautiful seaside resorts.",
    
    "Alicante": "A city on the eastern coast of Spain known for its long stretches of sandy beaches, including Playa del Postiguet and Playa de San Juan. The historic castle of Santa Bárbara, located on top of Mount Benacantil, offers stunning views of the city and the sea. Alicante is also known for its lively nightlife, with a variety of bars, clubs, and restaurants. The city hosts a number of festivals throughout the year, including the famous Hogueras de San Juan, a celebration of fire and light.",
    "Almería": "A city on the southeastern coast of Spain known for its beautiful natural surroundings, including the Sierra de Gádor mountain range and the Cabo de Gata-Níjar Natural Park. The city's historic center features landmarks like the Alcazaba of Almería, a Moorish fortress that dates back to the 10th century, and the Cathedral of Almería, a Gothic-style building from the 16th century. Almería is also a hub for film and TV production, with a number of Hollywood blockbusters and TV series filmed in the area.",
    "Asturias": "A region in northwestern Spain known for its lush landscapes, stunning coastline, and rich cultural heritage. The region offers a variety of outdoor activities, including hiking in the Picos de Europa mountains, surfing on the beaches of Gijón, and canoeing in the Sella River. The Camino de Santiago pilgrimage route passes through Asturias, with charming towns like Oviedo, Gijón, and Avilés offering a glimpse of the region's history and traditions. Asturian cuisine is also famous, with dishes like fabada asturiana (a hearty bean stew) and sidra (a sparkling apple cider) that are enjoyed throughout Spain.",
    "Bilbao": "A city in the Basque Country of northern Spain known for its stunning architecture, including the world-famous Guggenheim Museum, designed by Frank Gehry. The city also features a number of historic landmarks, such as the Gothic-style Bilbao Cathedral and the Mercado de la Ribera, one of the largest covered markets in Europe. Bilbao is known for its delicious Basque cuisine, with pintxos (bite-sized snacks) and txakoli (a local white wine) being popular choices. The nearby beaches of Bakio and Plentzia offer a great escape from the city.",
    "Barcelona": "A vibrant city on the northeastern coast of Spain known for its stunning architecture, including the famous works of Antoni Gaudí like the Sagrada Familia and Park Güell. The city is also home to the Gothic Quarter, a medieval neighborhood with narrow streets and historic buildings like the Cathedral of Barcelona. Visitors can enjoy the beaches of Barceloneta and the lively atmosphere of Las Ramblas, a popular pedestrian street lined with shops, restaurants, and street performers. The city also hosts major events like the Mobile World Congress and the Primavera Sound music festival.",
    "Badajoz": "A city in western Spain near the border with Portugal, Badajoz is known for its rich history and cultural heritage. The city's historic center features landmarks like the Alcazaba of Badajoz, a Moorish fortress from the 9th century, and the Cathedral of San Juan Bautista, a beautiful Gothic-style church. Badajoz also hosts a number of festivals throughout the year, including the Carnaval de Badajoz, one of the largest and most colorful carnivals in Spain. The city is also a great starting point for exploring the nearby countryside, with beautiful natural areas like the Sierra de Hornachos and the Guadiana International Bridge Park.",
    "Béziers": "A city in southern France near the border with Spain, Béziers is known for its rich history and beautiful architecture. The city's historic center features landmarks like the Saint-Nazaire Cathedral, a beautiful Gothic-style church, and the Plateau des Poètes, a park with beautiful sculptures and fountains. Béziers is also famous for its wine production, with vineyards and wineries dotting the countryside. The Canal du Midi, a UNESCO World Heritage site, runs through the city and offers a great way to explore the region by boat.",
    "Brindisi": "A city in southern Italy, Brindisi is known for its beautiful coastline, historic landmarks, and delicious cuisine. The city's historic center features landmarks like the Castello Svevo, a medieval fortress that now serves as a museum, and the Roman column, a monument that dates back to the 2nd century AD. Brindisi is also a hub for transportation, with a major port and airport connecting the city to other parts of Italy and Europe. The city is known for its seafood, pasta dishes, and local wines like Primitivo and Negroamaro.",
    "Donostia / San Sebastián": "A coastal city in the Basque Country of northern Spain, Donostia (also known as San Sebastián) is known for its stunning beaches, including La Concha and Zurriola, and its lively cultural scene. The city's historic center features landmarks like the Miramar Palace, a beautiful 19th-century building that now serves as a cultural center, and the Santa María del Coro Basilica, a beautiful Gothic-style church. Donostia is also famous for its culinary offerings, with a variety of pintxo bars and Michelin-starred restaurants serving up traditional Basque cuisine and innovative creations.",
    "Fuerteventura": "One of the Canary Islands off the coast of Africa, Fuerteventura is known for its beautiful beaches, stunning natural landscapes, and rich history. The island features a variety of outdoor activities, including windsurfing, hiking, and surfing. Visitors can explore the island's historic landmarks, such as the Betancuria Church, a beautiful Gothic-style church from the 17th century, and the Tindaya Mountain, an important site for the ancient Guanche people. Fuerteventura is also a great place to relax and unwind, with beautiful resorts and secluded beaches.",
    "Girona": "A city in northeastern Catalonia, Girona is known for its beautiful historic center, which features landmarks like the Girona Cathedral, a beautiful Gothic-style church, and the Arab Baths, a well-preserved Moorish bathhouse. The city's medieval walls offer stunning views of the surrounding countryside. Girona is also famous for its cuisine, with a variety of restaurants serving up traditional Catalan dishes like pa amb tomàquet (bread with tomato) and suquet de peix (a fish stew). The nearby Costa Brava offers beautiful beaches and picturesque seaside towns.",
    "Granada": "A city in southern Spain, Granada is known for its rich history, stunning architecture, and vibrant culture. The city's most famous landmark is the Alhambra, a stunning Moorish palace and fortress that dates back to the 14th century. The city's historic center features other important landmarks like the Cathedral of Granada, a beautiful Renaissance-style church, and the Sacromonte Abbey, a monastery built into the side of a hill. Granada is also known for its cultural offerings, including flamenco performances, music festivals, and traditional festivals like the Corpus Christi procession. The city is a great place to sample traditional Andalusian cuisine, with a variety of restaurants serving up dishes like gazpacho, tortilla de camarones (shrimp fritters), and paella.",
    "Ibiza": "An island in the Balearic Sea, Ibiza is known for its beautiful beaches, vibrant nightlife, and unique culture. The island is a popular destination for club-goers, with a variety of nightclubs and beach parties that attract visitors from around the world. Ibiza is also a great place to explore nature, with beautiful coastal trails and secluded coves. The island's historic center features landmarks like the Ibiza Cathedral, a beautiful Gothic-style church, and the Dalt Vila, a fortified hilltop town that offers stunning views of the surrounding area.",
    "Jerez de la Frontera": "A city in southern Spain, Jerez de la Frontera is known for its sherry production, beautiful architecture, and equestrian traditions. The city's historic center features landmarks like the Alcázar of Jerez de la Frontera, a beautiful Moorish fortress, and the Cathedral of San Salvador, a stunning Baroque-style church. Jerez is also known for its equestrian culture, with the Royal Andalusian School of Equestrian Art offering performances and training sessions. Visitors can sample the city's famous sherry at local wineries and bodegas, or enjoy traditional Andalusian cuisine at one of the city's many tapas bars and restaurants.",
    "A Coruña": "A city in northwestern Spain, A Coruña is known for its beautiful beaches, historic landmarks, and unique culture. The city's historic center features landmarks like the Tower of Hercules, a Roman lighthouse that is over 2,000 years old, and the Maria Pita Square, a beautiful plaza that is named after a local heroine. A Coruña is also a great place to sample Galician cuisine, with a variety of restaurants serving up dishes like pulpo a la gallega (octopus with paprika), empanadas (savory pastries), and tarta de Santiago (an almond cake). The nearby Rías Altas offer beautiful coastal landscapes and quaint fishing villages.",
    "Lanzarote": "One of the Canary Islands off the coast of Africa, Lanzarote is known for its unique volcanic landscapes, beautiful beaches, and rich cultural heritage. The island features a variety of outdoor activities, including hiking, surfing, and snorkeling. Visitors can explore the island's historic landmarks, such as the Cueva de los Verdes, a network of underground caves, and the Timanfaya National Park, a stunning volcanic landscape. Lanzarote is also a great place to relax and unwind, with beautiful resorts and secluded beaches.",
    "Madrid": "The capital city of Spain, Madrid is known for its stunning architecture, world-class museums, and vibrant culture. The city's historic center features landmarks like the Royal Palace of Madrid, a stunning Baroque-style palace that is the official residence of the Spanish royal family, and the Plaza Mayor, a beautiful square that has been the site of many historic events. Madrid is home to some of the world's most renowned museums, including the Prado Museum, which features an extensive collection of European art, and the Reina Sofía Museum, which is dedicated to modern and contemporary art. The city is also known for its lively food and nightlife scenes, with a variety of restaurants, bars, and clubs offering traditional Spanish cuisine and drinks. Madrid is a great place to experience the passion and energy of Spanish culture.",
    "Agadir": "A city on the Atlantic coast of Morocco, Agadir is known for its beautiful beaches, sunny weather, and relaxed atmosphere. The city features a long promenade lined with cafes, restaurants, and shops, and a beautiful marina where visitors can take boat trips or go fishing. Agadir is also a great place to explore Moroccan culture, with markets selling traditional crafts and souvenirs, and local restaurants serving up delicious Moroccan cuisine. The city's beautiful parks and gardens offer a peaceful escape from the hustle and bustle of the city.",
    "Menorca": "One of the Balearic Islands, Menorca is known for its beautiful beaches, turquoise waters, and relaxed atmosphere. The island is a great place to enjoy outdoor activities like hiking, cycling, and kayaking, and features a variety of historic landmarks like the Santa María Church and the Xoriguer Gin Distillery. Menorca is also known for its delicious food and drink, with local restaurants serving up dishes like caldereta de langosta (lobster stew) and ensaimada (a sweet pastry). The island's beautiful landscapes and charming towns offer a peaceful retreat from the stresses of everyday life.",
    "Melilla": "A Spanish enclave on the northern coast of Africa, Melilla is known for its unique blend of Spanish and Moroccan cultures. The city features a variety of historic landmarks, including the Melilla Cathedral and the Plaza de España, a beautiful square that is surrounded by palm trees and historic buildings. Melilla is also known for its lively food and nightlife scenes, with a variety of restaurants, bars, and clubs offering a mix of Spanish and Moroccan cuisine and drinks. Visitors can explore the city's markets and souks to discover traditional crafts and souvenirs.",
    "Palma, Majorca": "The capital city of the Balearic Islands, Palma is known for its beautiful beaches, historic landmarks, and vibrant culture. The city's historic center features landmarks like the Palma Cathedral, a stunning Gothic-style church, and the Bellver Castle, a beautiful 14th-century fortress that offers panoramic views of the city. Palma is also a great place to sample traditional Majorcan cuisine, with a variety of restaurants serving up dishes like sobrassada (a cured pork sausage) and tumbet (a vegetable stew). The city is a great base for exploring the rest of the island, which features beautiful landscapes and charming towns.",
    "Pamplona": "A city in northern Spain, Pamplona is known for its annual Running of the Bulls festival, as well as its beautiful architecture and rich history. The city's historic center features landmarks like the Pamplona Cathedral, a stunning Gothic-style church, and the Plaza del Castillo, a beautiful square that is surrounded by historic buildings. Pamplona is also a great place to sample traditional Basque cuisine, with a variety of restaurants serving up dishes like pintxos (small snacks served on bread) and txangurro (stuffed crab). The nearby Pyrenees offer beautiful landscapes and opportunities for outdoor activities like hiking and skiing.",
    "Santander": "A city in northern Spain, Santander is known for its beautiful beaches, historic landmarks, and relaxed atmosphere. The city's historic center features landmarks like the Santander Cathedral, a stunning Gothic-style church, and the Palacio de la Magdalena, a beautiful palace that was once the summer residence of the Spanish royal family. Santander is also a great place to sample traditional Cantabrian cuisine, with a variety of restaurants serving up dishes like cocido montañés (a hearty stew made with beans, cabbage, and pork) and quesada pasiega (a sweet dessert made with cheese). The city's beautiful parks and gardens offer a peaceful escape from the hustle and bustle of the city.",
    "Seville": "A city in southern Spain, Seville is known for its beautiful architecture, vibrant culture, and rich history. The city's historic center features landmarks like the Seville Cathedral, a stunning Gothic-style church that is the largest in the world, and the Alcázar of Seville, a beautiful palace that was once the residence of the Spanish royal family. Seville is also a great place to sample traditional Andalusian cuisine, with a variety of restaurants serving up dishes like gazpacho (a cold soup made with tomatoes, cucumbers, and peppers) and paella (a rice dish with seafood or meat). The city's lively food and nightlife scenes offer something for everyone.",
    "Tenerife": "The largest of the Canary Islands, Tenerife is known for its beautiful beaches, diverse landscapes, and vibrant culture. The island features a variety of outdoor activities like hiking, cycling, and surfing, as well as historic landmarks like the San Cristóbal de La Laguna Cathedral and the Tenerife Auditorium. Tenerife is also a great place to sample traditional Canarian cuisine, with a variety of restaurants serving up dishes like papas arrugadas (a salty boiled potato dish) and mojo verde (a green sauce made with garlic and herbs). The island's lively resorts offer a fun and festive atmosphere.",
    "Valencia": "A city on the eastern coast of Spain, Valencia is known for its beautiful beaches, historic landmarks, and vibrant culture. The city's historic center features landmarks like the Valencia Cathedral, a stunning Gothic-style church, and the City of Arts and Sciences, a futuristic complex of museums and performance spaces. Valencia is also a great place to sample traditional Valencian cuisine, with a variety of restaurants serving up dishes like paella (a rice dish with seafood or meat) and horchata (a sweet drink made with tiger nuts). The city's lively food and nightlife scenes offer something for everyone.",
    "Valladolid": "A city in central Spain, Valladolid is known for its beautiful architecture, historic landmarks, and rich culture. The city's historic center features landmarks like the Valladolid Cathedral, a stunning Gothic-style church, and the Plaza Mayor, a beautiful square that is surrounded by historic buildings. Valladolid is also a great place to sample traditional Castilian cuisine, with a variety of restaurants serving up dishes like lechazo asado (roast lamb) and sopa castellana (garlic soup). The city's museums and art galleries offer a glimpse into the region's rich history and culture.",
    "Vigo": "A city on the western coast of Spain, Vigo is known for its beautiful beaches, historic landmarks, and lively atmosphere. The city's historic center features landmarks like the Vigo Cathedral, a stunning Gothic-style church, and the Castro Fortress, a beautiful 17th-century fortress that offers panoramic views of the city. Vigo is also a great place to sample traditional Galician cuisine, with a variety of restaurants serving up dishes like pulpo a la gallega (Galician-style octopus) and empanada gallega (a savory pie filled with meat or fish). The city's lively markets and festivals offer a glimpse into the region's vibrant culture.",
    "Vitoria-Gasteiz": "The capital city of the Basque Country, Vitoria-Gasteiz is known for its beautiful parks and gardens, historic landmarks, and lively atmosphere. The city's historic center features landmarks like the Vitoria Cathedral, a stunning Gothic-style church, and the Plaza de la Virgen Blanca, a beautiful square that is surrounded by historic buildings. Vitoria-Gasteiz is also a great place to sample traditional Basque cuisine, with a variety of restaurants serving up dishes like pintxos (a type of Basque tapas) and bacalao al pil-pil (cod cooked in a garlic and chili sauce). The city's museums and art galleries offer a glimpse into the region's rich history and culture.",
    "Valverde": "A town on the island of El Hierro, Valverde is known for its beautiful natural scenery, historic landmarks, and quiet atmosphere. The town's historic center features landmarks like the Valverde Church, a stunning Gothic-style church, and the Mirador de la Peña, a beautiful viewpoint that offers panoramic views of the island. Valverde is also a great place to sample traditional Canarian cuisine, with a variety of restaurants serving up dishes like papas arrugadas (a salty boiled potato dish) and sancocho (a fish stew). The town's beautiful parks and gardens offer a peaceful escape from the hustle and bustle of the city.",
    "Zaragoza": "A city in northeastern Spain, Zaragoza is known for its beautiful architecture, historic landmarks, and lively atmosphere. The city's historic center features landmarks like the Zaragoza Cathedral, a stunning Gothic-style church, and the Aljafería Palace, a beautiful palace that was once the residence of the Moorish kings. Zaragoza is also a great place to sample traditional Aragonese cuisine, with a variety of restaurants serving up dishes like migas (a dish made with fried breadcrumbs and sausage) and ternasco asado (roast lamb). The city's museums and art galleries offer a glimpse into the region's rich history and culture.",
    "Santiago de Compostela": "A city in northwestern Spain, Santiago de Compostela is known for its beautiful architecture, historic landmarks, and religious significance. The city's historic center features landmarks like the Santiago de Compostela Cathedral, a stunning Gothic-style church that is the final destination of the Camino de Santiago pilgrimage route, and the Praza do Obradoiro, a beautiful square that is surrounded by historic buildings. Santiago de Compostela is also a great place to sample traditional Galician cuisine, with a variety of restaurants serving up dishes like pulpo a la gallega (Galician-style octopus) and empanada gallega (a savory pie filled with meat or fish). The city's museums and art galleries offer a glimpse into the region's rich history and culture."
    
    })
    
    return df


